### ISSUE TITLE
initiator_logical_address in common header

### ISSUE THREAD

**Issue by user4e32** [ienorand/spacewire-rmap#1]
https://github.com/ienorand/spacewire-rmap/blob/2820806fff21b38fd2c10995a3c75e315892061f/rmap.c#L418-L430

Line 418 or line 430 should be `header->initiator_logical_address`

?

**Comment by ienorand** [comment]
Yes, that's a bug, line 418 should be changed.

I have fixed this in the above linked commit.

Thanks for reporting!
